### ISSUE TITLE
Doesn't actually seem that much faster than vanilla?

### ISSUE THREAD

**Issue by IdrisQe** [ErrorMikey/AcceleratedDecay#2]
Maybe I'm misunderstanding what this mod does, but after installing v0.1.1 on my 1.18.2 Fabric server using Architectury 4.9.84 and Fabric 0.14.9, the leaves seem barely, if at all, any faster to decay. After chopping down a tree I can watch as each leaf individually takes anywhere between 1 and 10 seconds to decay. It's like the mod isn't even there. The leaves are all tagged as #minecraft:leaves too so that's not the problem. Not sure what exactly is going on?

I added this to the modpack Create: Astral v1.2, so perhaps some other mod is interfering somehow, not sure...

**Comment by MichaelHillcox** [comment]
Should be instant after a couple of ticks. Are you running a modpack?

**Comment by IdrisQe** [comment]
Yes, I said so at the end of my Issue. But that was a long while ago and I'm no longer using the mod, nor even the same version of Minecraft, so I can't really provide any more information.

**Comment by BigAl607** [comment]
> Should be instant after a couple of ticks. Are you running a modpack?

I'm running a 1.20.4 custom pack. The leaves aren't disappearing instantly. They make some kind of white powder-like stuff, but they're decaying very slowly.

NeoForge 21.4.30

Mod Version 21.0.0
