### ISSUE TITLE
no saplings

### ISSUE THREAD

**Issue by deadhitter1** [ErrorMikey/AcceleratedDecay#3]
this mod makes leaves no longer drop saplings. cut 7 acacia trees, 3 jungle ones, no other mods that do anything with leaves.
oh, and, to clear this up: breaking the leaves manually does drop saplings.
cut 28 more trees and yes, this mod straight up deletes leaves and does not have them drop anything.

**Comment by MichaelHillcox** [comment]
I'm unable to reproduce this, could you confirm the modpack you're using, if you're using one and the version of the mod
