### ISSUE TITLE
ConcurrentModificationException Crash

### ISSUE THREAD

**Issue by BumbleTree** [ErrorMikey/AcceleratedDecay#8]
Fabric 1.20.1
Running a Modded server, over the last week it has been crashing 1/3 times a day with ConcurrentModificationException and the crash logs were not helpful in pointing out the source, eventually removed this mod and it then it stopped crashing.

I ended up looking at the code and it does look like it could cause it so I modified the code myself and since then the server has not crashed and i have seen no issues with it so far.
Pull request is in #7 

Here is the crash log i kept getting
[2023-11-11-4.log](https://github.com/ErrorMikey/AcceleratedDecay/files/13329406/2023-11-11-4.log)

**Comment by MichaelHillcox** [comment]
Merged and shipped for 1.20.1! Thanks, I'll ship to 1.19.2 as well and prep a 1.20.2 release :grin:
